name: Build Risr

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Vulkan SDK & glslc
      run: sudo apt-get update && sudo apt-get install -y glslang-tools
    - name: Compile Shaders
      run: ./build_shaders.sh
    - name: Build with Gradle
      run: ./gradlew build
